const ROUTES_NAME: Record<string, string> = {
  dashboard: "الرئيسية",
  settings: "الإعدادات",
  clinics: "العيادات",
  doctors: "الأطباء",
  "working-days": "ايام العمل",
  create: "إضافة",
  update: "تعديل",
  employees: "الموظفين",
  patients: "المرضى",
  drugs: "الأدوية",
  treasuries: "الخزائن",
  expenses: "المصروفات",
  "expenses-categories": "تصنيفات المصروفات",
  bookings: "الحجوزات",
  transactions: "الإيرادات",
  "last-visits": "أخر الزيارات",
  analytics: "التحاليل",
  scans: "الأشعات",
  dosages: "الجرعات",
  prescriptions: "الروشتات",
  reports: "التقارير",
  transfers: "التحويلات",
  "patient-balances": "حسابات المرضى",
  transactionsReports: "تقارير الإيرادات",
  bookingsReports: "تقارير الحجوزات",
  expensesReports: "تقارير المصروفات",
  transfersReports: "تقارير التحويلات",
  prescriptionsReports: "تقارير الروشتات",
  treasuriesReports: "تقارير الخزائن",
  patientsReports: "تقارير المرضى",
  patientBalancesReports: "تقارير حسابات المرضى",
};

export default ROUTES_NAME;
